# Wrapper for freesurfer functions
# Copyright (C) 2021  Lisa Perus
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# long with this program.  If not, see <https://www.gnu.org/licenses/>.

# System import
import os


def parse_mri_segstats_output(mri_segstats_output, outdir):
    """ Parse Freesurfer mri_segstats output file
    ---------------------------------------------

    Parameters
    ----------
    mri_segstats_output: str
        path to mri_segstats output file.
    outdir: str
        path to output directory.

    Returns
    -------
    reg_stats: dict
        parsed mri_segstats output.
    """

    # Read file and find header line index
    header_idx = None
    with open(mri_segstats_output, "rt") as open_file:
        lines = open_file.readlines()
    for idx, line in enumerate(lines):
        if "ColHeaders" in line:
            header_idx = idx

    # Get for each region results
    reg_stats = {}
    header_split = lines[header_idx].split(" ")
    header_split = [
        x for x in header_split if len(x) != 0]
    for idx_line, line in enumerate(lines[header_idx + 1:]):
        line = line.split(" ")
        line = [x for x in line if len(x) != 0]
        reg_stats[idx_line] = {}
        for idx_elt, elt in enumerate(header_split):
            reg_stats[idx_line][elt] = line[idx_elt]
    return reg_stats


def save_tksurfer_im(tksurfer_cmd, output_file, fs_sh, tcl_script_file=None,
                     delete_tcl_script_file=True):
    """ Save an image generated by Freesurfer tksurfer viewer.

    TODO: Modify script. It is actually not working because of graphics.

    Parameters:
    -----------
    tksurfer_cmd: list of str
        tksurfer command.
    output_file: str
        path to output file.
    fs_sh: str
        path to Freesurfer setup file.
    tcl_script_file: str
        path to tcl script to save snapshot.
    delete_tcl_script_file: bool
        delete tcl file after command.
    """

    # Write tcl script
    if tcl_script_file is None:
        ext_output_file = os.path.splitext(output_file)[1]
        tcl_script_file = "tcl_script_" + output_file.replace(
            ext_output_file, ".tcl")
    with open(tcl_script_file, "wt") as open_file:
        open_file.write("save_tiff {0}\n".format(output_file))
        open_file.write("exit 0")

    # Run cmd
    cmd = tksurfer_cmd + ["-tcl", tcl_script_file]
    fscmd = FSWrapper(cmd, fs_sh)
    fscmd()

    # Delete tcl file if needed
    if delete_tcl_script_file:
        os.remove(tcl_script_file)
