# Wrapper for freesurfer functions
# Copyright (C) 2021  Lisa Perus
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# long with this program.  If not, see <https://www.gnu.org/licenses/>.

# System import
import os


def parse_mri_segstats_output(mri_segstats_output):
    """ Parse Freesurfer mri_segstats output file
    ---------------------------------------------

    Parameters
    ----------
    mri_segstats_output: str
        path to mri_segstats output file.

    Returns
    -------
    reg_stats: dict
        parsed mri_segstats output.
    """

    # Read file and find header line index
    header_idx = None
    header_line = "# ColHeaders  Index SegId NVoxels Volume_mm3 "
    header_line += "StructName Mean StdDev Min Max Range"
    with open(mri_segstats_output, "rt") as open_file:
        lines = open_file.readlines()
    for idx, line in enumerate(lines):
        if line.strip("\n").strip(" ") == header_line:
            header_idx = idx
    if header_idx is None:
        raise ValueError(
            "Could not find file {0} header".format(mri_segstats_output))

    # Index corresponding to element in line
    HEADER_PARSING = {0: "ColHeaders", 1: "Index_SegId", 2: "NVoxels",
                      3: "Volume_mm3", 4: "StructName",
                      5: "Mean_ct", 6: "StdDev_ct", 7: "Min_ct",
                      8: "Max_ct", 9: "Range_ct"}

    # Get for each region results
    reg_stats = {}
    for idx_line, line in enumerate(lines[header_idx + 1:]):
        line = line.strip("\n").split(" ")
        line = [x for x in line if len(x) != 0]
        if len(line) != len(list(HEADER_PARSING.keys())):
            raise ValueError(
                "Cannot find good number of element in line:\n {0}".format(
                    " ".join(line)))
        reg_stats[idx_line] = {}
        for idx_elt, elt in HEADER_PARSING.items():
            reg_stats[idx_line][elt] = line[idx_elt]
    return reg_stats


def save_tksurfer_im(tksurfer_cmd, output_file, fs_sh, tcl_script_file=None,
                     delete_tcl_script_file=True):
    """ Save an image generated by Freesurfer tksurfer viewer.

    TODO: Modify script. It is actually not working because of graphics.

    Parameters:
    -----------
    tksurfer_cmd: list of str
        tksurfer command.
    output_file: str
        path to output file.
    fs_sh: str
        path to Freesurfer setup file.
    tcl_script_file: str
        path to tcl script to save snapshot.
    delete_tcl_script_file: bool
        delete tcl file after command.
    """

    # Write tcl script
    if tcl_script_file is None:
        ext_output_file = os.path.splitext(output_file)[1]
        tcl_script_file = "tcl_script_" + output_file.replace(
            ext_output_file, ".tcl")
    with open(tcl_script_file, "wt") as open_file:
        open_file.write("save_tiff {0}\n".format(output_file))
        open_file.write("exit 0")

    # Run cmd
    cmd = tksurfer_cmd + ["-tcl", tcl_script_file]
    fscmd = FSWrapper(cmd, fs_sh)
    fscmd()

    # Delete tcl file if needed
    if delete_tcl_script_file:
        os.remove(tcl_script_file)


def parse_aseg_stats_file(aseg_stats_file):
    """ Parse Freesurfer aseg.stats file
    ---------------------------------------------

    Parameters
    ----------
    aseg_stats_file: str
        path to aseg stats file.

    Returns
    -------
    reg_stats: dict
        parsed aseg stats file.
    """

    # Read file and find header line index
    header_idx = None
    header_line = "# ColHeaders  Index SegId NVoxels Volume_mm3 StructName "
    header_line += "normMean normStdDev normMin normMax normRange"
    with open(aseg_stats_file, "rt") as open_file:
        lines = open_file.readlines()
    for idx, line in enumerate(lines):
        if line.strip("\n").strip(" ") == header_line:
            header_idx = idx
    if header_idx is None:
        raise ValueError(
            "Could not find file {0} header".format(aseg_stats_file))

    # Index corresponding to element in line
    HEADER_PARSING = {0: "ColHeaders", 1: "Index_SegId", 2: "NVoxels",
                      3: "Volume_mm3", 4: "StructName",
                      5: "normMean", 6: "normStdDev", 7: "normMin",
                      8: "normMax", 9: "normRange"}

    # Get for each region results
    reg_stats = {}
    for idx_line, line in enumerate(lines[header_idx + 1:]):
        line = line.strip("\n").split(" ")
        line = [x for x in line if len(x) != 0]
        if len(line) != len(list(HEADER_PARSING.keys())):
            raise ValueError(
                "Cannot find good number of element in line:\n {0}".format(
                    " ".join(line)))
        reg_stats[idx_line] = {}
        for idx_elt, elt in HEADER_PARSING.items():
            reg_stats[idx_line][elt] = line[idx_elt]
    return reg_stats
